default_twitter: &default_twitter
  twitter_api_key: 'YdDN9BGdqLDvmbOkad99eZiao'
  twitter_api_secret: 'QyXyxPTeawJJwnrQXKoZRdBWJPRSsYr37J7WAkg1vCWEy25CxW'

development:
  secret_key_base: 287c189f7d09accf67e47ffe47f7e54b6247760cc54f25c1369bdca82c970445a501df6dd24ee537d7e221b62f2ff3c9bcf2587f18bfded895b14f72ec036819
  <<: *default_twitter

test:
  secret_key_base: f6a4152dd1b538fa16cd7e893628cfaacb559db88dd0e4c6c7906a5e5116d483cf0972c707663328fb5d9664db865622f4b10f5e8e2550385717a372d62d5124
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
